# Wrapper around a locally-run transformer model for speech fluency classification.
# The model runs on Apple Silicon using PyTorch with MPS (Metal Performance Shaders) backend — set via
# torch.device("mps") if available, fallback to CPU.
# The model to use is wav2vec2-base fine-tuned for fluency/confidence classification (or a similar audio
# classification model from HuggingFace).
# This module is NOT called during live sessions — it is called only during post-session analysis to score
# each segment of the session transcript for fluency, confidence, and clarity. Results feed into the coaching
# report generated by POST /sessions/{id}/report.
